version: '3.8'
services:
  db-mysql:
    image: mysql:5.7.40
    restart: always
    environment:
      - MYSQL_DATABASE=iot_mo_cua_thong_minh
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3307:3306"
    expose:
      - 3306
  smart-unlock:
    build:
      context: ../sm
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3306
      - DB_HOST=db-mysql
    ports:
      - 8080:8080
    expose:
      - 8080
  nginx:
    image: nginx:1.26.0
    ports:
      - 80:80
    volumes:
      - ../sm/default.conf:/etc/nginx/conf.d/default.conf

#docker compose -p smartunlock up -d (--build  #nếu muốn build lại + xoá cache)